# Generated by Django 4.1.2 on 2022-11-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('positiveNumber', models.IntegerField()),
                ('negativeNumber', models.IntegerField()),
                ('neutralNumber', models.IntegerField()),
                ('historyRank', models.TextField(default='')),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('attitude', models.CharField(max_length=50)),
                ('retrievetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Twitters',
            },
        ),
    ]
