# Generated by Django 4.1.2 on 2022-11-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextEmotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='negativeNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='neutralNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='positiveNumber',
            field=models.IntegerField(null=True),
        ),
    ]
